In [1]:
import sys
import os
import pandas as pd
import numpy as np
import time
import requests

In [21]:
player_stats=pd.read_html('https://www.hockey-reference.com/leagues/NHL_2007_skaters.html')
new_df=pd.DataFrame(player_stats[0])

if isinstance(new_df.columns, pd.MultiIndex):
    # Replace the top header with the subheader
    new_df.columns = new_df.columns.get_level_values(1)

new_df=new_df.reset_index(drop=True)
new_df

,Rk,Player,Age,Tm,Pos,GP,G,A,PTS,+/-,...,PP,SH,GW,EV,PP,SH,S,S%,TOI,ATOI
0,1,Ramzi Abid,26,NSH,LW,13,1,4,5,-3,...,0,0,0,4,0,0,12,8.3,141,10:51
1,2,Craig Adams,29,CAR,RW,82,7,7,14,-9,...,0,1,1,6,0,1,71,9.9,826,10:04
2,3,Kevyn Adams,32,TOT,C,68,3,9,12,-20,...,0,1,0,7,1,1,87,3.4,742,10:55
3,3,Kevyn Adams,32,CAR,C,35,2,2,4,-10,...,0,1,0,2,0,0,36,5.6,303,8:39
4,3,Kevyn Adams,32,PHX,C,33,1,7,8,-10,...,0,0,0,5,1,1,51,2.0,440,13:20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1066,856,Sergei Zubov*,36,DAL,D,78,12,42,54,0,...,9,0,3,11,31,0,156,7.7,2024,25:57
1067,857,Dainius Zubrus,28,TOT,RW,79,24,36,60,-19,...,10,0,4,23,13,0,158,15.2,1540,19:29
1068,857,Dainius Zubrus,28,WSH,RW,60,20,32,52,-16,...,9,0,4,20,12,0,127,15.7,1191,19:51
1069,857,Dainius Zubrus,28,BUF,RW,19,4,4,8,-3,...,1,0,0,3,1,0,31,12.9,349,18:22
1070,858,Andrei Zyuzin,29,CGY,D,49,1,5,6,-2,...,0,0,0,5,0,0,36,2.8,677,13:49

In [32]:
count=2008
all_df_skaters=pd.DataFrame()
all_df_goalies=pd.DataFrame()
while count>=1996:
  url_skaters=f'https://www.hockey-reference.com/leagues/NHL_{count}_skaters.html'
  url_goalies=f'https://www.hockey-reference.com/leagues/NHL_{count}_goalies.html'
  df_skaters = pd.read_html(url_skaters)
  df_goalies = pd.read_html(url_goalies)
  df_skaters_cleaned=pd.DataFrame(df_skaters[0])
  df_goalies_cleaned=pd.DataFrame(df_goalies[0])
  if isinstance(df_skaters_cleaned.columns, pd.MultiIndex):
    df_skaters_cleaned.columns = df_skaters_cleaned.columns.get_level_values(1)
  if isinstance(df_goalies_cleaned.columns, pd.MultiIndex):
    df_goalies_cleaned.columns = df_goalies_cleaned.columns.get_level_values(1)
  df_skaters_cleaned=df_skaters_cleaned.drop_duplicates(['Rk'], keep='first')
  df_goalies_cleaned=df_goalies_cleaned.drop_duplicates(['Rk'], keep='first')
  df_skaters_cleaned['SEASON']=count
  df_goalies_cleaned['SEASON']=count
  # df_skaters_cleaned=df_skaters_cleaned.reset_index(inplace=True, drop=True)
  if len(all_df_skaters)>0:
    all_df_skaters=all_df_skaters.reset_index(inplace=True)
  all_df_skaters = pd.concat([all_df_skaters, df_skaters_cleaned], axis=0)
  all_df_goalies=pd.concat([all_df_goalies, df_goalies_cleaned], axis=0)
  count-=1

HTTPError: HTTP Error 429: Too Many Requests

In [31]:
all_df_skaters

,Rk,Player,Age,Tm,Pos,GP,G,A,PTS,+/-,...,SH,GW,EV,PP,SH,S,S%,TOI,ATOI,SEASON
0,1,Ramzi Abid,25,ATL,LW,6,0,2,2,1,...,0,0,2,0,0,6,0.0,49,8:10,2006
1,2,Craig Adams,28,CAR,RW,67,10,11,21,1,...,1,2,9,0,2,68,14.7,824,12:18,2006
2,3,Kevyn Adams,31,CAR,C,82,15,8,23,0,...,2,2,7,0,1,160,9.4,1057,12:53,2006
3,4,Dmitry Afanasenkov,25,TBL,LW,68,9,6,15,-7,...,0,0,3,3,0,78,11.5,662,9:44,2006
4,5,Maxim Afinogenov,26,BUF,RW,77,22,51,73,6,...,0,3,31,20,0,241,9.1,1258,16:20,2006
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1099,866,Marek Å½idlickÃ½,28,NSH,D,67,12,37,49,8,...,0,1,18,19,0,113,10.6,1344,20:04,2006
1100,867,Mike Zigomanis,25,TOT,C,23,1,0,1,1,...,0,0,0,0,0,17,5.9,213,9:16,2006
1103,868,Sergei Zubov*,35,DAL,D,78,13,58,71,20,...,0,0,28,30,0,141,9.2,2047,26:15,2006
1104,869,Dainius Zubrus,27,WSH,RW,71,23,34,57,3,...,0,5,19,13,2,181,12.7,1446,20:22,2006
1105,870,Andrei Zyuzin,28,MIN,D,57,7,11,18,-12,...,0,1,7,4,0,80,8.8,1076,18:53,2006

In [13]:
all_df_skaters

In [5]:
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.model_selection import train_test_split

skaters_df=pd.read_csv('/Users/hinayatali/Desktop/MIE368_PROJECT/team_proj/skaters_2009_2023.csv', index_col=None)
goalies_df=pd.read_csv('/Users/hinayatali/Desktop/MIE368_PROJECT/team_proj/goalies_2009_2023.csv', index_col=None)

skater_pred_vars=['Age', 'Pos', 'GP', 'G', 'A', 'PTS', '+/-', 'PIM', 'EV', 'PP', 'SH', 'EV', 'PP', 'SH', 'S', 'S%', 'TOI', 'ATOI', 'BLK', 'HIT', 'FOW', 'FO%']
goalie_pred_vars=['Age', 'GP', 'GS', 'W', 'L', 'T/O', 'GA', 'SA', 'SV', 'SV%', 'GAA', 'SO', 'MIN' , 'QS', 'QS%', 'RBS', 'GA%-', 'GSAA']

skater_target_var=['PS']
goalie_target_var=['GPS']

# X_train, X_test, y_train, y_test = train_test_split( 
#              skaters_df[training_cols], y, test_size = 0.2, random_state=42)

In [140]:
# testing_url_skaters=f'https://www.hockey-reference.com/leagues/NHL_2008_skaters.html'
# testing_url_skaters_2=f'https://www.hockey-reference.com/leagues/NHL_2007_skaters.html'
# df_skaters_1 = pd.read_html(testing_url_skaters)
# df_skaters_2 = pd.read_html(testing_url_skaters_2)
# df_skaters_1_cleaned=pd.DataFrame(df_skaters_1[0])
# df_skaters_2_cleaned=pd.DataFrame(df_skaters_2[0])
# if isinstance(df_skaters_1_cleaned.columns, pd.MultiIndex):
#     df_skaters_1_cleaned.columns = df_skaters_1_cleaned.columns.get_level_values(1)
# if isinstance(df_skaters_2_cleaned.columns, pd.MultiIndex):
#     df_skaters_2_cleaned.columns = df_skaters_2_cleaned.columns.get_level_values(1)
# df_skaters_1_cleaned=df_skaters_1_cleaned.drop_duplicates(['Rk'], keep='first')
# df_skaters_2_cleaned=df_skaters_2_cleaned.drop_duplicates(['Rk'], keep='first')


df_skaters_1_cleaned_copied=df_skaters_1_cleaned.copy()
df_skaters_2_cleaned_copied=df_skaters_2_cleaned.copy()

df_skaters_1_cleaned_copied['SEASON']=2008
df_skaters_2_cleaned_copied['SEASON']=2007

df_skaters_1_cleaned_copied.set_index(drop=True, inplace=True)
df_skaters_2_cleaned_copied.set_index(drop=True, inplace=True)

# set(df_skaters_1_cleaned_copied.columns)-set(df_skaters_2_cleaned_copied.columns)

# df_skaters_2_cleaned_copied[['BLK','FO%','FOL','FOW','HIT']]=np.nan

# df_skaters_1_cleaned_copied

# df_skaters_1_cleaned_copied
# df_skaters_1_cleaned_copied=df_skaters_1_cleaned_copied.reset_index()
# selected_columns = df_skaters_1_cleaned_copied.columns[1:]  # Select all columns from the second column onward
# df_skaters_1_cleaned_copied=df_skaters_1_cleaned_copied[selected_columns].reset_index(drop=True, inplace=True)
# selected_columns = df_skaters_2_cleaned_copied.columns[1:]  # Select all columns from the second column onward
# df_skaters_2_cleaned_copied=df_skaters_2_cleaned_copied[selected_columns].reset_index(drop=True, inplace=True)


# duplicates = df_skaters_2_cleaned_copied.index.duplicated()
# duplicate_rows = df_skaters_2_cleaned_copied[duplicates]
# print(duplicate_rows)
df_skaters_1_cleaned_copied=df_skaters_1_cleaned_copied.set_index('Rk').reset_index(drop=True)
df_skaters_2_cleaned_copied=df_skaters_2_cleaned_copied.set_index('Rk').reset_index(drop=True)
# df_skaters_1_cleaned_copied=df_skaters_1_cleaned_copied.reset_index(drop=True)
# df_skaters_2_cleaned_copied=df_skaters_2_cleaned_copied.reset_index(drop=True)
# df_skaters_2_cleaned_copied
# df_skaters_1_cleaned_copied.index
# df_skaters_1_cleaned_copied.
pd.concat([df_skaters_1_cleaned_copied, df_skaters_2_cleaned_copied], axis=0, ignore_index=True)

InvalidIndexError: Reindexing only valid with uniquely valued Index objects

In [12]:
player='Rasmus Dahlin'

skaters_df.loc[skaters_df['Player']==player]

pos=skaters_df.loc[(skaters_df['Pos']=="D") & (skaters_df['Age']=='18') & (skaters_df['Player']!=player)]
pos

,Unnamed: 0,Rk,Player,Age,Tm,Pos,GP,G,A,PTS,...,S,S%,TOI,ATOI,BLK,HIT,FOW,FOL,FO%,SEASON
2177,253,220,Jamie Drysdale,18,ANA,D,24,3,5,8,...,28,10.7,470,19:35,23,7,0,0,NaN,2021
2936,73,65,Tobias BjÃ¶rnfot,18,LAK,D,3,0,0,0,...,0,NaN,39,12:58,0,0,0,0,NaN,2020
3221,428,350,Ville Heinola,18,WPG,D,8,1,4,5,...,10,10.0,145,18:04,5,3,0,0,NaN,2020
5677,146,124,Jakob Chychrun,18,ARI,D,68,7,13,20,...,86,8.1,1133,16:40,99,109,0,0,NaN,2017
6278,863,725,Mikhail Sergachev,18,MTL,D,4,0,0,0,...,2,0.0,49,12:08,3,10,0,0,NaN,2017
6884,521,442,Oliver Kylington,18,CGY,D,1,0,0,0,...,1,0.0,17,17:22,1,0,0,0,NaN,2016
7556,272,215,Aaron Ekblad,18,FLA,D,81,12,27,39,...,170,7.1,1767,21:49,80,109,0,0,NaN,2015
9101,1038,877,Nikita Zadorov,18,BUF,D,7,1,0,1,...,4,25.0,120,17:10,3,25,0,0,NaN,2014
12673,66,55,Zach Bogosian,18,ATL,D,47,9,10,19,...,90,10.0,851,18:06,50,67,0,0,NaN,2009

In [24]:
def marcels_projection_system_player(player_name, season, df):
    df['SEASON']=df['SEASON'].astype(int)
    ps_list=df.loc[(df['Player']==player_name) & (df['SEASON']>=season-2)]
    ps_list
    return ps_list
    
marcels_projection_system_player('Rasmus Dahlin', 2023, skaters_df)

,Unnamed: 0,Rk,Player,Age,Tm,Pos,GP,G,A,PTS,...,S,S%,TOI,ATOI,BLK,HIT,FOW,FOL,FO%,SEASON
179,222,179,Rasmus Dahlin,22,BUF,D,78,15,58,73,...,204,7.4,2012,25:48,132,105,0,0,NaN,2023
1141,242,189,Rasmus Dahlin,21,BUF,D,80,13,40,53,...,170,7.6,1921,24:01,91,121,0,0,NaN,2022
2142,217,185,Rasmus Dahlin,20,BUF,D,56,5,18,23,...,115,4.3,1210,21:36,45,80,0,0,NaN,2021